# Configuration about data preprocessing
data: Machine_Util
target: m_2                                  # Specify the target to use; only used in M, MS mood
features: "S"                                # M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate
seq_len: 18                                  # Length of input series
label_len: 6                                 # Length of label in input series' tail
pred_len: 12                                 # Length of predict series
freq: "s"
scale: True
standardlize_method: "MinMax"                # If scale==True, choose 'Standard' or 'Minmax'
num_workers: 6

# Configuration about the structure of model and the hyperparameters
is_training: 1
model_id: "FEDformer_train"
task_id: "Machine_Util_1"                    # task id
model: "FEDformer"                           # Specify the model framework to use
learning_rate: 0.0001
loss: "MSELoss"
delta: 0.1                                   # only for Huber loss
batch_size: 128
n_heads: 8                                   # Number of heads
d_model: 512                                 # Depth of model
dropout: 0.05                                # Dropout rate
factor: 3                                    # Attention factor proposed in origin paper
d_ff: 2048                                   # Dimension of FCN
activation: "gelu"
moving_avg: 25
c_out: 1                                     # Output feature number
version: "Fourier"                           # Fourier mode or wavelet mode
e_layers: 4                                  # encoder_layers
enc_in: 1                                    # encoder_input_size
d_layers: 3                                  # decoder_layers
dec_in: 1                                    # decoder_input_size

# Configuration about training and pedrict, test_ratio is (1 - train_ratio - vali_ratio), so no need to specify test_ratio
train_ratio: 0.7
vali_ratio: 0.2
train_epochs: 100
itr: 1                                       # Number of experiment times  
patience: 5                                  # early stopping patience                                                             
detail_freq: "s"

# Configuration about the dataset
root_path: ./dataset/Machine_Util/           # root path of the data file
data_path: machine_util_m_2.csv              # data file


# optional settings, not needed most of the time
random_seed: 2021                            
output_attention: False
cross_activation: "tanh"
do_predict: False
lradj: "type3"
regularization: False
lambda_l1: 0.1
